### ISSUE TITLE
This is great! Can you add testing though?

### ISSUE THREAD

**Issue by jimrazmus** [msfidelis/serverless-architecture-boilerplate#2]
I think that adding a set of unit tests would complement this boilerplate and help people new to Serverless.

Regardless, thanks for assembling and sharing this project!

**Comment by msfidelis** [comment]
Yeah! This is a great idea!
But, a need help to find a simple and lightweight way to mock AWS Resources locally.
Do you have suggestions?

**Comment by msfidelis** [comment]
I'm create this PR to give an start to unit tests. 
https://github.com/msfidelis/serverless-architecture-boilerplate/pull/3
